name: deploy

on: [push]
    
jobs:
  
  test-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say test-job
        run: echo "This is job for testing!"

  before-prod:
    runs-on: ubuntu-latest
    
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say before-prod
        run: echo "This is job before-prod!"
  
  prod:
    runs-on: ubuntu-latest
    
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    environment: Production
    
    needs: [before-prod]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say prod
        run: echo "This is job prod!"

  after-prod:
    runs-on: ubuntu-latest
    
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    needs: [prod]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say after-prod
        run: echo "This is job after-prod"
  
