name: Hello World

# Kích hoạt khi có push code
on: [push]

jobs:
  
  before-prod:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say before-prod
        run: echo "This is job before-prod!"
  
  prod:
    runs-on: ubuntu-latest
    
    environment: Production
    
    needs: [before-prod]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say prod
        run: echo "This is job prod!"

  after-prod:
    runs-on: ubuntu-latest
    
    needs: [prod]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say after-prod
        run: echo "This is job after-prod"
